const typeArray = [
    "afghan",
    "african american",
    "argentinian",
    "austrian",
    "dutch",
    "belgian",
    "brazilian",
    "burmese",
    "cambodian",
    "english",
    "ethiopian",
    "filipino",
    "finish",
    "german",
    "french",
    "hungarian",
    "indian",
    "iranian",
    "irish",
    "israeli",
    "italian",
    "japanese",
    "korean",
    "lebanese",
    "iraqi",
    "egyptian",
    "chad-cameroon",
    "chinese",
    "mexican",
    "mongolian",
    "peruvian",
    "russian",
    "samoan",
    "puerto rican",
    "polish",
    "saudi",
    "serbian",
    "south african",
    "south indian",
    "spanish",
    "swedish",
    "swiss",
    "taiwanese",
    "thai",
    "tibetan",
    "turkish",
    "ukranian",
    "uzbek",
    "vietnamese",
    "welsh",
    "west african",
    "white american",
  ];

  export default typeArray